### ISSUE TITLE
apax add fails - package seems missing

### ISSUE THREAD

**Issue by christof-ochs** [simatic-ax/commands#2]
**Description**
After logging into the the github registry, I want to add the commands package to my project (using apax add @simatic-ax/commands).
Fails with the following message:
_Usage Error: You have no permission to install package "@simatic-ax/commands" from registry "https://npm.pkg.github.com/".
 If the resolved registry isn't the expected one, check your apax.yml and global config for the correct registry entries.
 If this package is expected to be from the Simatic-AX registry, check that you have access to that namespace.
 To get a list of all accessible scopes execute 'apax info --ax-scopes'._

There is no release package in this repository.

This is not in alignment with the documented usage of the package. For a public repository on the SIMATIC AX GitHub Community I would expect a release package.

**To Reproduce**
1. Create AX workspace
2. Add simatic-ax registry to apax.yml
3. Execute "apax add @simatic-ax/commands"

**Expected behavior**
Dependency is added to apax.yml and package is downloaded.

**Screenshots**
![image](https://github.com/simatic-ax/commands/assets/115996212/49cf3767-bd89-4d0f-bbaa-403e612aad8d)

**Comment by sjuergen** [comment]
@christof-ochs the package is available but it was private. Now it should work
